### ISSUE TITLE
How to generate the .csv files for the graph?

### ISSUE THREAD

**Issue by Youmna-Salah** [BatsResearch/zsl-kg#7]
Hello,
I was trying to run your code for a different dataset and was wondering how can I get the ids in the [nodes.csv](https://github.com/BatsResearch/zsl-kg/blob/master/tutorials/knowledge_graph/nodes.csv) file?

**Comment by nihalnayak** [comment]
Thanks for the question. I have included utilities to query the ConceptNet graph in https://github.com/BatsResearch/nayak-arxiv20-code/tree/master/graph_utils. You may find this helpful. Let me know if you have any more questions.

**Comment by Youmna-Salah** [comment]
Thank you for the link, Do you have any links for the conceptnet.db file? I downloaded one from ' https://conceptnet-lite.fra1.cdn.digitaloceanspaces.com/conceptnet.db.zip' but it has a different format than the ones that you used because the code expects some fields that don't exist in the file.

**Comment by nihalnayak** [comment]
I used the ConceptNetDB from https://github.com/BatsResearch/taglets. You can download the DB with the following command: 
```
wget -nc https://storage.googleapis.com/taglets-public/scads.spring2021.sqlite3
```
You may have to change `DATABASE_PATH` in `main.py` to `scads.spring2021.sqlite3`. Let me know if this works for you.
